export const productData = {
  desktops: [
    {
      id: 1,
      brand: "Acer ",
      model: "Nitro50 ",
      purpose: "( Gaming )",
      price: "RF 11,900",
      cpu: "8th Gen Intel Core i5",
      cpu_model: "-8400",
      gpu: "AMD Radeon RX 580",
      ram: "8GB DDR4 ",
      ram_speed: "2666MHz RAM",
      vram: "4GB GDDR5",
      hdd: "1TB",
      hdd_speed: "7200RPM",
      SSD: "",
      optical_drive: "8X DVD-Writer",
      optical_drive_details: "Double-Layer Drive (DVD-RW)",
      img: "img/Acer-Nitro50-N50-600.jpg",
    },
    {
      id: 2,
      brand: "Hp",
      model: "Pavilion TP01-0034",
      purpose: "( Media )",
      price: "RF 12,990",
      cpu: "Intel® Core™ i7",
      cpu_model: "-8700",
      gpu: "Intel® UHD Graphics 630",
      ram: "8GB DDR4 ",
      ram_speed: "2666MHz RAM",
      vram: "",
      hdd: "1TB",
      hdd_speed: "7200RPM",
      SSD: "",
      optical_drive: "8X DVD-Writer",
      optical_drive_details: "Double-Layer Drive (DVD-RW)",
      img: "img/Hp-Pavilion-TP01-0034.jpg",
    },
    {
      id: 3,
      brand: "Acer ",
      model: "Nitro50 ",
      purpose: "( Gaming )",
      price: "RF 11,900",
      cpu: "8th Gen Intel Core i5",
      cpu_model: "-8400",
      gpu: "AMD Radeon RX 580",
      ram: "8GB DDR4 ",
      ram_speed: "2666MHz RAM",
      vram: "4GB GDDR5",
      hdd: "1TB",
      hdd_speed: "7200RPM",
      SSD: "",
      optical_drive: "8X DVD-Writer",
      optical_drive_details: "Double-Layer Drive (DVD-RW)",
      img: "img/Acer-Nitro50-N50-600.jpg",
    },
    {
      id: 4,
      brand: "Hp",
      model: "Pavilion TP01-0034",
      purpose: "( Media )",
      price: "RF 12,990",
      cpu: "Intel® Core™ i7",
      cpu_model: "-8700",
      gpu: "Intel® UHD Graphics 630",
      ram: "8GB DDR4 ",
      ram_speed: "2666MHz RAM",
      vram: "",
      hdd: "1TB",
      hdd_speed: "7200RPM",
      SSD: "",
      optical_drive: "8X DVD-Writer",
      optical_drive_details: "Double-Layer Drive (DVD-RW)",
      img: "img/Hp-Pavilion-TP01-0034.jpg",
    },
  ],
  laptops: [
    {
      id: 1,
      brand: "Lenovo",
      model: "Ideapad 330-15IGM (81D1)",
      purpose: "( Media )",
      price: "RF 7,900",
      cpu: "Intel Celeron Dual Core",
      cpu_model: "-N4000 / 1.1 Ghz",
      gpu: "Intel HD Graphics 500",
      ram: "4GB DDR4 ",
      ram_speed: "2666MHz RAM",
      vram: "2GB DDR4",
      hdd: "512GB",
      hdd_speed: "SSD",
      SSD: "",
      optical_drive: "8X DVD-Writer",
      optical_drive_details: "Double-Layer Drive (DVD-RW)",
      img: "img/Lenovo-Ideapad-330-15IGM-81D1-image-1-720x720.jpg",
    },
    {
      id: 2,
      brand: "Asus",
      model: "F510QA-DS99",
      purpose: "( Media )",
      price: "RF 9,200",
      cpu: "Intel Celeron Dual Core",
      cpu_model: "-N4000 / 1.1 Ghz",
      gpu: "Intel HD Graphics 500",
      ram: "4GB DDR4 ",
      ram_speed: "2666MHz RAM",
      vram: "2GB DDR4",
      hdd: "512GB",
      hdd_speed: "SSD",
      SSD: "",
      optical_drive: "8X DVD-Writer",
      optical_drive_details: "Double-Layer Drive (DVD-RW)",
      img: "img/Asus-F510QA-DS99-image-2-720x720.jpg",
    },
    {
      id: 3,
      brand: "Asus",
      model: "ROG Hero Edition GL503GE-US72",
      purpose: "( Gaming )",
      price: "RF 18,500",
      cpu: "Intel Core i7",
      cpu_model: "-8750H Processor 2.2GHz",
      gpu: "NVIDIA GeForce GTX 1050 Ti",
      ram: "8GB DDR4 ",
      ram_speed: "3000MHz RAM",
      vram: "6GB DDR4",
      hdd: "128GB",
      hdd_speed: "SSD",
      SSD: "",
      optical_drive: "8X DVD-Writer",
      optical_drive_details: "Double-Layer Drive (DVD-RW)",
      img: "img/Asus-ROG-Hero-Edition-GL503GE-US72-image-1-720x720.jpg",
    },
  ],
};
